version: '3.2'

services:

  # local development (watches files)
  develop:
    build:
        context: .
        dockerfile: Dockerfile
        args:
          - LASTCOMMIT
    ports:
      - 9085:8081
    volumes:
      - .:/workspace

  # jest tests
  test:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/workspace
    command: "npm test"
    environment:
      - LASTCOMMIT

      # production container
  production:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - LASTCOMMIT
    volumes:
      - .:/workspace
    ports:
      - 9085:8080
    command: "node app.bundle.js"
